version: '3.3'
services:
  nginx:
    entrypoint: ["echo", "Service nginx disabled"]
    restart: "no"
  api:
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEVELOPMENT=true
    volumes:
      - ./api:/webapp/api
      - ./media:/webapp/media
  frontend:
    environment:
      - DJANGO_DEVELOPMENT=true
    volumes:
      - ./frontend/src:/webapp/frontend/src
    restart: always
  celery:
    environment:
      - DJANGO_DEVELOPMENT=true
    volumes:
      - ./api:/webapp/api
      - ./media:/webapp/media
