services:
  nginx:
    build: ./nginx
  api:
    build:
      context: .
      dockerfile: gpu.Dockerfile
  celery-fast:
    build:
      context: .
      dockerfile: gpu.Dockerfile
  celery-slow:
    build:
      context: .
      dockerfile: gpu.Dockerfile
  frontend:
    build: ./frontend
