# Generated by Django 3.1.2 on 2020-12-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicmix',
            name='celery_id',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='staticmix',
            name='celery_id',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ytaudiodownloadtask',
            name='celery_id',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
