# Generated by Django 3.1.4 on 2020-12-23 21:56

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201218_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicmix',
            name='demucs_shifts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dynamicmix',
            name='separator',
            field=models.CharField(choices=[(api.models.Separator['SPLEETER'], 'Spleeter'), ('demucs', ((api.models.Separator['DEMUCS'], 'Demucs'), (api.models.Separator['DEMUCS_EXTRA'], 'Demucs (extra)'), (api.models.Separator['DEMUCS_LIGHT'], 'Demucs Light'), (api.models.Separator['DEMUCS_LIGHT_EXTRA'], 'Demucs Light (extra)'), (api.models.Separator['TASNET'], 'Tasnet'), (api.models.Separator['TASNET_EXTRA'], 'Tasnet (extra)')))], default=api.models.Separator['SPLEETER'], max_length=20),
        ),
        migrations.AddField(
            model_name='staticmix',
            name='demucs_shifts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staticmix',
            name='separator',
            field=models.CharField(choices=[(api.models.Separator['SPLEETER'], 'Spleeter'), ('demucs', ((api.models.Separator['DEMUCS'], 'Demucs'), (api.models.Separator['DEMUCS_EXTRA'], 'Demucs (extra)'), (api.models.Separator['DEMUCS_LIGHT'], 'Demucs Light'), (api.models.Separator['DEMUCS_LIGHT_EXTRA'], 'Demucs Light (extra)'), (api.models.Separator['TASNET'], 'Tasnet'), (api.models.Separator['TASNET_EXTRA'], 'Tasnet (extra)')))], default=api.models.Separator['SPLEETER'], max_length=20),
        ),
    ]
