# Generated by Django 3.1.4 on 2020-12-24 02:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201218_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicmix',
            name='random_shifts',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='dynamicmix',
            name='separator',
            field=models.CharField(choices=[('spleeter', 'Spleeter'), ('demucs', (('demucs', 'Demucs'), ('demucs_extra', 'Demucs (extra)'), ('light', 'Demucs Light'), ('light_extra', 'Demucs Light (extra)'), ('tasnet', 'Tasnet'), ('tasnet_extra', 'Tasnet (extra)')))], default='spleeter', max_length=20),
        ),
        migrations.AddField(
            model_name='staticmix',
            name='random_shifts',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='staticmix',
            name='separator',
            field=models.CharField(choices=[('spleeter', 'Spleeter'), ('demucs', (('demucs', 'Demucs'), ('demucs_extra', 'Demucs (extra)'), ('light', 'Demucs Light'), ('light_extra', 'Demucs Light (extra)'), ('tasnet', 'Tasnet'), ('tasnet_extra', 'Tasnet (extra)')))], default='spleeter', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='staticmix',
            unique_together={('source_track', 'separator', 'random_shifts', 'vocals', 'drums', 'bass', 'other')},
        ),
    ]
