# Generated by Django 3.1.4 on 2020-12-25 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201224_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicmix',
            name='source_track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic', to='api.sourcetrack'),
        ),
        migrations.AlterUniqueTogether(
            name='dynamicmix',
            unique_together={('source_track', 'separator', 'random_shifts')},
        ),
    ]
