# Generated by Django 3.2.3 on 2021-05-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210107_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicmix',
            name='separator',
            field=models.CharField(choices=[('spleeter', 'Spleeter'), ('demucs', (('demucs', 'Demucs'), ('demucs48_hq', 'Demucs HQ'), ('demucs_extra', 'Demucs Extra'), ('demucs_quantized', 'Demucs Quantized'), ('tasnet', 'Tasnet'), ('tasnet_extra', 'Tasnet Extra'))), ('xumx', 'X-UMX')], default='spleeter', max_length=20),
        ),
        migrations.AlterField(
            model_name='staticmix',
            name='separator',
            field=models.CharField(choices=[('spleeter', 'Spleeter'), ('demucs', (('demucs', 'Demucs'), ('demucs48_hq', 'Demucs HQ'), ('demucs_extra', 'Demucs Extra'), ('demucs_quantized', 'Demucs Quantized'), ('tasnet', 'Tasnet'), ('tasnet_extra', 'Tasnet Extra'))), ('xumx', 'X-UMX')], default='spleeter', max_length=20),
        ),
    ]
