# Generated by Django 3.2.4 on 2021-06-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210614_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicmix',
            name='separator',
            field=models.CharField(choices=[('spleeter', 'Spleeter'), ('d3net', 'D3Net'), ('demucs', (('demucs', 'Demucs'), ('demucs48_hq', 'Demucs HQ'), ('demucs_extra', 'Demucs Extra'), ('demucs_quantized', 'Demucs Quantized'), ('tasnet', 'Tasnet'), ('tasnet_extra', 'Tasnet Extra'), ('light', 'Demucs Light'), ('light_extra', 'Demucs Light Extra'))), ('xumx', 'X-UMX')], default='spleeter', max_length=20),
        ),
        migrations.AlterField(
            model_name='staticmix',
            name='separator',
            field=models.CharField(choices=[('spleeter', 'Spleeter'), ('d3net', 'D3Net'), ('demucs', (('demucs', 'Demucs'), ('demucs48_hq', 'Demucs HQ'), ('demucs_extra', 'Demucs Extra'), ('demucs_quantized', 'Demucs Quantized'), ('tasnet', 'Tasnet'), ('tasnet_extra', 'Tasnet Extra'), ('light', 'Demucs Light'), ('light_extra', 'Demucs Light Extra'))), ('xumx', 'X-UMX')], default='spleeter', max_length=20),
        ),
    ]
