# Generated by Django 3.2.12 on 2022-02-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211217_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicmix',
            name='date_finished',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='staticmix',
            name='date_finished',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ytaudiodownloadtask',
            name='date_finished',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
