# Generated by Django 4.1.5 on 2023-01-08 22:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_dynamicmix_bitrate_alter_staticmix_bitrate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staticmix',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dynamicmix',
            name='piano_file',
            field=models.FileField(blank=True, default=None, max_length=255, null=True, upload_to=api.models.mix_track_path),
        ),
        migrations.AddField(
            model_name='staticmix',
            name='piano',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dynamicmix',
            name='separator',
            field=models.CharField(choices=[('spleeter', 'Spleeter'), ('spleeter_5stems', 'Spleeter 5 stems'), ('d3net', 'D3Net'), ('demucs', (('htdemucs', 'Demucs v4'), ('htdemucs_ft', 'Demucs v4 Fine-tuned'), ('hdemucs_mmi', 'Demucs v3 MMI'), ('mdx', 'Demucs v3'), ('mdx_extra', 'Demucs v3 Extra'), ('mdx_q', 'Demucs v3 Quantized'), ('mdx_extra_q', 'Demucs v3 Extra Quantized'), ('demucs', 'Demucs'), ('demucs48_hq', 'Demucs HQ'), ('demucs_extra', 'Demucs Extra'), ('demucs_quantized', 'Demucs Quantized'), ('tasnet', 'Tasnet'), ('tasnet_extra', 'Tasnet Extra'), ('light', 'Demucs Light'), ('light_extra', 'Demucs Light Extra'))), ('xumx', 'X-UMX')], default='spleeter', max_length=20),
        ),
        migrations.AlterField(
            model_name='staticmix',
            name='separator',
            field=models.CharField(choices=[('spleeter', 'Spleeter'), ('spleeter_5stems', 'Spleeter 5 stems'), ('d3net', 'D3Net'), ('demucs', (('htdemucs', 'Demucs v4'), ('htdemucs_ft', 'Demucs v4 Fine-tuned'), ('hdemucs_mmi', 'Demucs v3 MMI'), ('mdx', 'Demucs v3'), ('mdx_extra', 'Demucs v3 Extra'), ('mdx_q', 'Demucs v3 Quantized'), ('mdx_extra_q', 'Demucs v3 Extra Quantized'), ('demucs', 'Demucs'), ('demucs48_hq', 'Demucs HQ'), ('demucs_extra', 'Demucs Extra'), ('demucs_quantized', 'Demucs Quantized'), ('tasnet', 'Tasnet'), ('tasnet_extra', 'Tasnet Extra'), ('light', 'Demucs Light'), ('light_extra', 'Demucs Light Extra'))), ('xumx', 'X-UMX')], default='spleeter', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='staticmix',
            unique_together={('source_track', 'separator', 'separator_args', 'bitrate', 'vocals', 'drums', 'bass', 'other', 'piano')},
        ),
    ]
