# Generated by Django 3.0.5 on 2020-04-26 02:35

import app.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tmp/', validators=[app.validators.is_valid_size, app.validators.is_mp3])),
            ],
        ),
        migrations.CreateModel(
            name='SourceSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('source_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.SourceFile')),
            ],
        ),
        migrations.CreateModel(
            name='SeparatedSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocals', models.BooleanField()),
                ('drums', models.BooleanField()),
                ('bass', models.BooleanField()),
                ('other', models.BooleanField()),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'In Progress'), (3, 'Done')], default=1)),
                ('file', models.FileField(blank=True, upload_to='')),
                ('source_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SourceSong')),
            ],
            options={
                'unique_together': {('source_song', 'vocals', 'drums', 'bass', 'other')},
            },
        ),
    ]
