# Generated by Django 3.0.5 on 2020-04-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='separatedsong',
            unique_together=set(),
        ),
    ]
