# Generated by Django 3.0.5 on 2020-05-09 19:21

import app.models
import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcefile',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=app.models.source_file_path, validators=[app.validators.is_valid_size, app.validators.is_mp3]),
        ),
    ]
