# Generated by Django 3.0.5 on 2020-05-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200509_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='separatedsong',
            name='file',
            field=models.FileField(blank=True, max_length=255, upload_to='separate'),
        ),
    ]
