# Generated by Django 3.0.5 on 2020-05-10 01:01

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200509_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='separatedsong',
            name='file',
            field=models.FileField(blank=True, max_length=255, upload_to=app.models.sep_song_path),
        ),
    ]
