valid_signal_idx: 1600
type: MMD3Netv3
band_split_idxs: [192]
num_init_features: [32, 8]
num_layer_blocks: [[4, 5, 5, 4, 4, 4, 4], [1, 1, 1, 1, 1, 1, 1]]
dens_k: [[16, 18, 18, 20, 18, 16, 16], [2, 2, 2, 2, 2, 2, 2]]
b_n_blocks: [[2, 2, 2, 2, 2, 2, 2], [1, 1, 1, 1, 1, 1, 1]]
comp_rates: [[1.0, 1.0, 1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]]
f_num_init_features: 30
f_num_layer_block: [3, 3, 3, 5, 7, 5, 3, 2, 2]
f_dens_k: [10, 10, 12, 14, 16, 14, 12, 8, 8]
f_n_blocks: [2, 2, 2, 2, 2, 2, 2, 2, 2]
f_comp_rates: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
ttl_num_layer_block: 3
ttl_dens_k: 14
cuda: True
load_all: True
patch_length: 352
n_channels: 2
fft_size: 4096
hop_size: 1024
fs: 44100
target_instruments: [bass]
target_clop: 0
use_batchrenorm: False
num_patches_val: 8
test_patch_len: 384
out_shift: 192
out_clop: 0