valid_signal_idx: 1600
type: MMD3Netv3
band_split_idxs: [128]
num_init_features: [32, 8]
num_layer_blocks: [[5, 5, 5, 4, 4, 4, 4], [1, 1, 1, 1, 1]]
dens_k: [[16, 18, 20, 22, 20, 18, 16], [2, 2, 2, 2, 2]]
b_n_blocks: [[2, 2, 2, 2, 2, 2, 2], [1, 1, 1, 1, 1]]
comp_rates: [[1.0, 1.0, 1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0, 1.0]]
f_num_init_features: 32
f_num_layer_block: [4, 5, 6, 7, 8, 6, 5, 4, 4]
f_dens_k: [13, 14, 15, 16, 17, 16, 14, 12, 11]
f_n_blocks: [2, 2, 2, 2, 2, 2, 2, 2, 2]
f_comp_rates: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
ttl_num_layer_block: 3
ttl_dens_k: 12
cuda: True
load_all: True
ds: True
patch_length: 256
n_channels: 2
fft_size: 4096
hop_size: 1024
fs: 44100
target_instruments: [drums]
target_clop: 0
weight_decay: 0.0001
use_batchrenorm: False
num_patches_val: 8
test_patch_len: 256
out_shift: 128
out_clop: 0