valid_signal_idx: 1600
type: MMD3Netv3
band_split_idxs: [256]
num_init_features: [32, 8]
num_layer_blocks: [[4, 5, 5, 6, 4, 4, 4], [1, 1, 1, 1, 1]]
dens_k: [[14, 15, 16, 18, 16, 14, 14], [2, 2, 2, 2, 2]]
b_n_blocks: [[2, 2, 2, 2, 2, 2, 2], [1, 1, 1, 1, 1]]
comp_rates: [[1.0, 1.0, 1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]]
f_num_init_features: 30
f_num_layer_block: [3, 4, 6, 7, 8, 5, 4, 3, 3]
f_dens_k: [11, 12, 13, 14, 16, 14, 12, 11, 10]
f_n_blocks: [2, 2, 2, 2, 2, 2, 2, 2, 2]
f_comp_rates: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
ttl_num_layer_block: 3
ttl_dens_k: 12
cuda: True
load_all: True
ds: True
patch_length: 256
n_channels: 2
fft_size: 4096
hop_size: 1024
fs: 44100
target_instruments: [other_instr]
target_clop: 0
weight_decay: 0.0001
use_batchrenorm: False
num_patches_val: 8
test_patch_len: 256
out_shift: 128
out_clop: 0
amp: True