name: Docker Compose push (release)

on:
  release:
    types: [ created ]

jobs:
  build-cpu:
    name: Build and publish CPU images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.DOCKER_USERNAME }}
        # Container registry password
        password: ${{ secrets.DOCKER_TOKEN }}
        # Container registry server url
        login-server: https://index.docker.io/v1/

    - name: Build images (release)
      run: docker-compose -f docker-compose.yml -f docker-compose.build.yml build
      env:
        TAG: ${{ github.event.release.tag_name }}

    - name: Push images to Docker Hub (release)
      run: docker-compose -f docker-compose.yml -f docker-compose.build.yml push
      env:
        DOCKER_CLIENT_TIMEOUT: 180
        COMPOSE_HTTP_TIMEOUT: 180
        TAG: ${{ github.event.release.tag_name }}

  build-gpu:
    name: Build and publish GPU images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.DOCKER_USERNAME }}
        # Container registry password
        password: ${{ secrets.DOCKER_TOKEN }}
        # Container registry server url
        login-server: https://index.docker.io/v1/

    - name: Free disk space
      uses: jlumbroso/free-disk-space@v1.3.0
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Build GPU images (release)
      run: docker-compose -f docker-compose.gpu.yml -f docker-compose.build.gpu.yml build api
      env:
        TAG: ${{ github.event.release.tag_name }}

    - name: Push GPU images to Docker Hub (release)
      run: docker-compose -f docker-compose.gpu.yml -f docker-compose.build.gpu.yml push api
      env:
        DOCKER_CLIENT_TIMEOUT: 180
        COMPOSE_HTTP_TIMEOUT: 180
        TAG: ${{ github.event.release.tag_name }}
