# This is a basic workflow to help you get started with Actions

name: Docker Compose push (release)

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [ created ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Docker login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.DOCKER_USERNAME }}
        # Container registry password
        password: ${{ secrets.DOCKER_TOKEN }}
        # Container registry server url
        login-server: https://index.docker.io/v1/

    - name: Build images (release)
      run: docker-compose -f docker-compose.yml -f docker-compose.build.yml build
      env:
        TAG: ${{ github.event.release.tag_name }}

    - name: Push images to Docker Hub (release)
      run: docker-compose -f docker-compose.yml -f docker-compose.build.yml push
      env:
        DOCKER_CLIENT_TIMEOUT: 180
        COMPOSE_HTTP_TIMEOUT: 180
        TAG: ${{ github.event.release.tag_name }}
